#!/usr/bin/env perl

use strict;
use warnings;

die qq{Usage:$0 <node> <name> \
Example: taxon-db nodes.dmp  names.dmp  >taxon.map\n} if( @ARGV != 2 );

my ($node, $name) = @ARGV;
my %tax_name  = ();

load_name();
print_node();

exit;

sub load_name{
    
    open (DATA ,       $name) || die "$!"; 
    while(<DATA>){
        my @its = split /\s+\|\s+/ , $_;    
        if(/scientific name/){
            $tax_name{  $its[0] }  = $its[1];
        }
    }
    close DATA;

}

sub print_node{

    my %rank_h = qw/subspecies - strain - isolate -  genus - family - species -  phylum  - class -  order - kingdom - superkingdom - /;

    open (DATA,         $node) || die "$!";
    while (<DATA>) {
       my @its = split /\s+\|\s+/ , $_;
       if(exists  $rank_h{$its[2]}){
          print qq{$its[0]\t$its[1]\t$its[2]\t$tax_name{ $its[0] }\t$tax_name{$its[1]}\n};
       }else{
          print qq{$its[0]\t$its[1]\tno rank\t$tax_name{ $its[0] }\t$tax_name{$its[1]}\n};
       }
    }
    close DATA;
}

